vim.loader.enable()

require("plugins.plugins-setup")
require("core.keymaps")
require("core.options")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.noice")
-- require("plugins.lsp")
-- require("plugins.lspsaga")
require("plugins.cmp")
-- require("plugins.autopairs")
require("plugins.comment")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
require("plugins.indent")
